app/Http/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/','AuthController@index');



Route::get('noticia', 'AuthController@vernoticia');

Route::get('registro', function () {
    return view('auth/registro');
});


Route::get('miasoguau', 'AuthController@miasoguauindex');

Route::get('noticiaAsored', function () {
    return view('auth/miasoguau/nuevaNoticiaAsored');
});

Route::get('donacion', function () {
    return view('auth/creardonacion');
});

Route::get('login', 'AuthController@showLogin'); // Mostrar login
Route::post('login', 'AuthController@postLogin'); // Verificar datos
Route::get('logout', 'AuthController@logOut'); // Finalizar sesión

Route::post('crearusuarios','AuthController@store');

Route::post('crearAsored','AuthController@crearAsored');
//Route::get('login', 'LoginController@showLogin');
//Route::post('login', 'AuthController@postLogin');

/* Rutas del Backend */

Route::get('backend', 'UsuarioController@backend');

/*
 * Estas rutas son rutas de tipos RESTFull cada una son rutas que tienen
 * los metodos necesarios para realizar el CRUD, traten de separar
 * cada rute Resource y sus metodos de elemento inactivo (si aplica)
 * y el metodo de retornar el elemento
 *
 * Se comentará cada ruta para tener un control del mismo
 * */

/*
 * Resource
 * Veterinarios Inactivos
 * Recovery de Veterinarios
 * */
Route::resource('vets', 'VeterinarioController');


/*
 * Resource
 * Usuarios Inactivos
 * Recovery de Usuarios
 * */

Route::resource('usuarios', 'UsuarioController');
Route::get('usuarios_inactivos', 'UsuarioController@inactivos');
Route::post('retorno/{id}', 'UsuarioController@activos'); //Usuarios



/*
*Resoruces
*Noticias Inactivas
*Recovery de Noticias
*/

Route::resource('noticiasbackend', 'NoticiaController');
Route::get('noticias_inactivos', 'NoticiaController@inactivos');
Route::post('retornonoticias/{id}', 'NoticiaController@activos'); //Usuarios


/*
*Resoruces
*Donaciones Inactivas
*Recovery de Donaciones
*/

Route::resource('donacionesbackend', 'DonacionController');
Route::get('donaciones_inactivos', 'DonacionController@inactivos');
Route::post('retornodonaciones/{id}', 'DonacionController@activos'); //Usuarios



/*
*Resoruces
*Donaciones Inactivas
*Recovery de Donaciones
*/

Route::resource('animales', 'AnimalController');
Route::get('animales_inactivos', 'AnimalController@inactivos');
Route::post('retornoanimales/{id}', 'AnimalController@activos'); //Usuarios


/*
*Resoruces
*Donaciones Inactivas
*Recovery de Donaciones
*/

Route::resource('especies', 'EspecieController');
Route::get('especies_inactivos', 'EspecieController@inactivos');
Route::post('retornoespecies/{id}', 'EspecieController@activos'); //Usuarios

resources/views/backend/base.blade.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Asoguau Backend</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet" />
    <!-- FONTAWESOME ICONS STYLES-->
    <link href="{{ asset('assets/css/font-awesome.css') }}" rel="stylesheet" />
    <!--CUSTOM STYLES-->
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" />
    <link href="{{ asset('icons/flaticon.css') }}" rel="stylesheet">
    <link href="{{ asset('icons2/flaticon.css') }}" rel="stylesheet">
    <!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div id="wrapper">
    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a  class="navbar-brand" href="index.html">Asoguau

            </a>
        </div>

        <div class="notifications-wrapper">
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user-plus"></i> Opciones de Usuario <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user-plus"></i> My Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-sign-out"></i> Logout</a>
                        </li>
                    </ul>
                </li>

            </ul>

        </div>
    </nav>
    <!-- /. NAV TOP  -->
    <nav  class="navbar-default navbar-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="main-menu">
                <li>
                    <div class="user-img-div">
                        <img src="{{ asset('img/user.png') }}" class="img-circle" />
                    </div>
                </li>
                <li>
                    <a  href="#"> <strong> {!! Auth::user()->nombre !!} {!! Auth::user()->apellido !!} </strong></a>
                </li>

                <li>
                    <a class="active-menu"  href="{{ url('backend') }}"><i class="fa fa-dashboard "></i>Dashboard</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-sitemap "></i>M&oacute;dulos <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="#"><i class="fa fa-cogs "></i>Usuarios<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="{{ route('usuarios.index') }}"><i class="glyphicon glyphicon-briefcase"></i>
                                        Administrar</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-thumbs-up"></i>Activos</a>
                                </li>
                                <li>
                                    <a href="{{ url('usuarios_inactivos') }}"><i class="fa fa-thumbs-down"></i>Inactivos</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="{{ route('noticiasbackend.index') }}"><i class="fa fa-dashcube "></i>Noticias</a>
                        </li>

                        <li>
                            <a href="{{ route('donacionesbackend.index') }}"><i class="fa fa-dashcube "></i>Donaciones</a>
                        </li>

                        <li>
                            <a href="#"><i class="flaticon-health10 "></i>Veterinarios<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="{{ route('vets.index') }}"><i class="glyphicon glyphicon-briefcase"></i>
                                        Administrar</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-thumbs-up"></i>Activos</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-thumbs-down"></i>Inactivos</a>
                                </li>

                            </ul>
                        </li>


                        <li>
                            <a href="#"><i class="fa fa-paw"></i>Mascotas<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="{{ route('animales.index') }}"><i class="fa fa-paw"></i>Datos Mascota<span class="fa arrow"></span></a>
                                    
                                </li>
                                <li>
                                    <a href="{{ route('especies.index') }}"></i>Especies<span class="fa arrow"></span></a>
                                    
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                
            </ul>
        </div>

    </nav>
    <!-- /. SIDEBAR MENU (navbar-side) -->
    @yield('contenedor')
</div>
<footer >
    &copy; 2015 Asoguau | By : <a target="_blank">Alumnos de Sistema de Informaci&oacute;n II</a>
</footer>
<!-- /. FOOTER  -->
<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
<!-- JQUERY SCRIPTS -->
<script src="{{ asset('assets/js/jquery-1.11.1.js') }}"></script>
<!-- BOOTSTRAP SCRIPTS -->
<script src="{{ asset('assets/js/bootstrap.js') }}"></script>
<!-- METISMENU SCRIPTS -->
<script src="{{ asset('assets/js/jquery.metisMenu.js') }}"></script>
<!-- CUSTOM SCRIPTS -->
<script src="{{ asset('assets/js/custom.js') }}"></script>


</body>
</html>

resources/views/backend/index.blade.php
@extends('backend.base')

@section('contenedor')
        <div id="page-wrapper" class="page-wrapper-cls">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">DASHBOARD</h1>
                    </div>
                </div>
                <div class="row">
                    <div class=" col-md-3 col-sm-3">
                        <div class="style-box-one Style-one-clr-one">
                            <a href="#">
                                <span class="glyphicon glyphicon-headphones"></span>
                                <h5>Some Sample Text</h5>
                            </a>
                        </div>
                    </div>
                    <div class=" col-md-3 col-sm-3">
                        <div class="style-box-one Style-one-clr-two">
                            <a href="#">
                                <span class="glyphicon glyphicon-repeat"></span>
                                <h5>Some Sample Text</h5>
                            </a>
                        </div>
                    </div>
                    <div class=" col-md-3 col-sm-3">
                        <div class="style-box-one Style-one-clr-three">
                            <a href="#">
                                <span class="glyphicon glyphicon-camera"></span>
                                <h5>Some Sample Text</h5>
                            </a>
                        </div>
                    </div>
                    <div class=" col-md-3 col-sm-3">
                        <div class="style-box-one Style-one-clr-four">
                            <a href="#">
                                <span class="glyphicon glyphicon-cog"></span>
                                <h5>Some Sample Text</h5>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>First Name</th>
                                    <th>Username</th>
                                    <th>User No.</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>1</td>
                                    <td><span class="label label-primary">Lolo Bird</span></td>
                                    <td>@twitter</td>
                                    <td>100090</td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Otto</td>
                                    <td>@mdo</td>
                                    <td><span class="label label-info">100090</span></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Thornton</td>
                                    <td>@fat</td>
                                    <td>100090</td>
                                </tr>

                                <tr>
                                    <td>4</td>
                                    <td><span class="label label-primary">the Bird</span></td>
                                    <td>@twitter</td>
                                    <td>100090</td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td><span class="label label-success">Thornton</span></td>
                                    <td>@fat</td>
                                    <td><span class="label label-danger">100090</span></td>
                                </tr>

                                <tr>
                                    <td>6</td>
                                    <td>Otto</td>
                                    <td>@mdo</td>
                                    <td><span class="label label-info">100090</span></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
                <!-- /. PAGE INNER  -->
            </div>
            <!-- /. PAGE WRAPPER  -->
        </div>
    <!-- /. WRAPPER  -->
@endsection